// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslkseafliendnmkenez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbGtzZWFmbGllbmRubWtlbmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTk5NDIsImV4cCI6MjA1NjY3NTk0Mn0.C2B5ZUJrd6tkJJEGTUs_o8kh-ez5OjuPzHArApfEO8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);